name: Siali GH Action template

on:
  push:
    branches: [ $default-branch ]
  pull_request:
  
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: Sialitech/.github-private/workflows/job1.yml@main
    name: run reusable workflow
